### ISSUE TITLE
Change Pin Item Color if text is written on it

### ISSUE THREAD

**Issue by akankshapaul048** [ChaosLeung/PinView#43]
What kind of issue is this?

 - [ ] Question. If you want to ask how to do something, or to understand why something isn't
       working the way you expect it to.

 - [ ] Bug report. Please provide your device name, device OS version, and describe the reproduction steps.

 - [1] Feature Request. Telling us what problem you’re trying to solve.

##### Info:

 * PinView version: 1.4.3
 * Device OS version: Oreo
 * Device Name: Realme 3 Pro

##### What did I do:

**Comment by rmdan90** [comment]
I want the same effect in my app, Did you find a solution?

**Comment by akankshapaul048** [comment]
@rmdan90 I did that by changing the code of pinview

in drawPinView() method update

boolean highlight = isFocused() && highlightIdx == i;
to 
boolean highlight = isFocused() && highlightIdx <= i;

And it will work like a charm.
Let me know if any problem.

**Comment by rmdan90** [comment]
@akankshapaul048 Thank you, works like a charm.
