### ISSUE TITLE
Can't switch between hide and view password

### ISSUE THREAD

**Issue by syyam** [ChaosLeung/PinView#52]
What kind of issue is this?

 - [ ] Feature Request. A function that switch the view between password view to text view.

##### Info:

 * PinView version: 1.4.3
 * Device OS version: 9
 * Device Name: Oneplus5

##### Description:
Is there a clever way to let the user switch between hide and view password in an android PinView? A number of apps let the user do this.

##### What did I do:
In layout file I have by defauult made the PinVew's password label to true, now I want to disable the view using a button. In code i tried `pinView.setTransformationMethod(new PasswordTransformationMethod());` but it doesn't do anything.

**Comment by ChaosLeung** [comment]
`EditText.setInputType` can archive this.

example:

```java
setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD)
setInputType(InputType.TYPE_CLASS_TEXT)
```

See Also: [Programmatically change input type of the EditText from PASSWORD to NORMAL & vice versa](https://stackoverflow.com/a/9893496/3351990)
