### ISSUE TITLE
Enable Similar softkeyboard for Pin and Password

### ISSUE THREAD

**Issue by anandwana001** [ChaosLeung/PinView#55]
What kind of issue is this?

 - [x] Feature Request. Telling us what problem you’re trying to solve.

##### Info:

 * PinView version: 1.4.3
 * Device OS version: API 28
 * Device Name: Pixel

##### Description:
I am using PinView as a toggle option for password input with the show and hide option where I am changing showing and hiding number using InputType.TYPE_CLASS_NUMBER and InputType.TYPE_NUMBER_VARIATION_PASSWORD. But while toggling between the showing and hiding thing, the soft keyboard is also changing. 

Is there a way to have consistent keyboard?

**Comment by ChaosLeung** [comment]
It has been fixed in #54 but not release yet. And I will make a release this weekend.

**Comment by anandwana001** [comment]
> It has been fixed in #54 but not release yet. And I will make a release this weekend.

Cool, Thanks for update

**Comment by ChaosLeung** [comment]
Please upgrade to 1.4.4 and use `setPasswordHidden` to show or hide pins.
