### ISSUE TITLE
JCenter is shutting down, are there plans to migrate?

### ISSUE THREAD

**Issue by sapuglha** [ChaosLeung/PinView#58]
What kind of issue is this?

 - [X] Question. If you want to ask how to do something, or to understand why something isn't
       working the way you expect it to.

 - [ ] Bug report. Please provide your device name, device OS version, and describe the reproduction steps.

 - [ ] Feature Request. Telling us what problem you’re trying to solve.

##### Description:
JCenter is shutting down, are there plans to migrate? - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ChaosLeung** [comment]
Yes. But maybe take some time.

**Comment by ChaosLeung** [comment]
``` groovy
repositories {
    maven {
        mavenCentral()
    }
}

dependencies {
   implementation 'io.github.chaosleung:pinview:1.4.4'
}
```

Now you can use maven central to import the library. Because I am not the owner of view.chaos.com, the group id on maven central has been changed to `io.github.chaosleung`.

**Comment by mwshubham** [comment]
Thanks for the update. And your PR will help me to migrate one of my library to maven central as well. Thanks a lot.
