### ISSUE TITLE
crash when using line viewType

### ISSUE THREAD

**Issue by peyman86** [ChaosLeung/PinView#59]
Hello,
I'm using pinView version 1.4.4 but, when I change viewType to "line", I will get an error inflating

**Comment by ChaosLeung** [comment]
Can you provide the crash log?

**Comment by dima-ko** [comment]
```
     Caused by: java.lang.IllegalArgumentException: The itemRadius can not be greater than lineWidth when viewType is line
        at com.chaos.view.PinView.checkItemRadius(PinView.java:250)
E:     at com.chaos.view.PinView.<init>(PinView.java:170)
        at com.chaos.view.PinView.<init>(PinView.java:126)
        	... 28 more
```

**Comment by ChaosLeung** [comment]
@dima-ko My fault, in fact, the `itemRadius` must less than or equals half of `lineWidth`. Take a look at [`PinView#checkItemRadius()`](https://github.com/ChaosLeung/PinView/blob/master/pinview/src/main/java/com/chaos/view/PinView.java#L246)

**Comment by dima-ko** [comment]
on https://github.com/ChaosLeung/PinView page in XML example if you change **app:viewType** from **rectangle** to **line**, app will crash. I don't think it should be like this

**Comment by ChaosLeung** [comment]
Because PinView allow use rounded corners for rectangle or line (actually the line is also drawn by a rectangle path). So, if you specify a radius, PinView does not allow the radius greater than half of the width.

**Comment by peyman86** [comment]
Thank you so much @ChaosLeung My problem is solved with your guide , I will close issue
