### ISSUE TITLE
Error inflating class com.chaos.view.PinView

### ISSUE THREAD

**Issue by mhoseini967** [ChaosLeung/PinView#63]
Error inflating class com.chaos.view.PinView

IllegalArgumentException
The itemRadius can not be greater than itemWidth

android version: 10, 11

libraryVersion:1.4.3

**Comment by mhoseini967** [comment]
fixed it by replace:

 app:itemRadius="16sp" 
to  
 app:itemRadius="16dp"

**Comment by ChaosLeung** [comment]
Have a look of [this](https://github.com/ChaosLeung/PinView/issues/59#issuecomment-811070321).
